### ISSUE TITLE
서버 리팩토링

### ISSUE THREAD

**Issue by cca-company** [NHNNEXT/2015-03-DEVWEB-UNDEFINED#27]

**Comment by GingerAebi** [comment]
- BlockController -> Block Service 이름 변경
- GetBlockListServlet, PostBlockListServlet -> BlockListController로 합침
  - URL : /blockList 로 변경

**Comment by GingerAebi** [comment]
질문 
- BlockService에서 BlockValidateChecker를 호출하는 것이 좋을까요? 아니면 지금처럼 Controller에서 직접 호출하는 것이 나을까요?
